#Co trzeba zrobić:
# docker pull container-registry.oracle.com/database/express:latest
#docker-compose up-d
#połączyć się z bazą na localhoscie z portem 1521 użytkownik system hasło ligmus
services:
  oracle-db:
    image: container-registry.oracle.com/database/express:latest
    container_name: oracle-demo
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PWD=ligmus
    volumes:
      - oracle-data:/opt/oracle/oradata # Path for persistent data
volumes:
  oracle-data: